// Generated by CoffeeScript 2.5.1
(function() {
  $(function() {
    var deleted, disable_autoplay;
    deleted = false;
    (disable_autoplay = function() { // Called immediately
      var autoplay, autoplay_btn, chkbox;
      autoplay = $('div.checkbox-on-off, div#head.ytd-compact-autoplay-renderer');
      chkbox = autoplay.find('input, paper-toggle-button');
      autoplay_btn = $('div.ytp-right-controls > button[data-tooltip-target-id="ytp-autonav-toggle-button"]');
      if (autoplay.length === 0) {
        autoplay = null;
      }
      if (autoplay_btn.length === 0) {
        autoplay_btn = null;
      }
      if (!deleted && (autoplay == null) && (autoplay_btn == null)) {
        return setTimeout(disable_autoplay, 1000);
      }
      if ((autoplay != null) && (chkbox != null)) {
        if (chkbox.attr('checked')) { // Disable autoplay if enabled
          chkbox.click();
        }
        autoplay.remove(); // Delete the autoplay div
        return deleted = true;
      } else if (autoplay_btn != null) {
        if (autoplay_btn.attr('title').search(/is on/gi) === -1) {
          return deleted = true;
        } else {
          autoplay_btn.click();
          // May not have clicked immediately, give it another try
          return setTimeout(disable_autoplay, 1000);
        }
      }
    })();
    return $(this).on('spfdone yt-navigate-finish viewport-load', disable_autoplay); // Call when the page navigates
  });

}).call(this);
