// Generated by CoffeeScript 1.12.1
(function() {
  $(function() {
    var disable_autoplay;
    (disable_autoplay = function() {
      var autoplay, chkbox;
      autoplay = $('div.checkbox-on-off');
      chkbox = autoplay.find('input');
      if ((autoplay != null) && (chkbox != null)) {
        if (chkbox.is(':checked')) {
          chkbox.click();
        }
        return autoplay.remove();
      }
    })();
    return $(this).on('spfdone', disable_autoplay);
  });

}).call(this);
